name: 'ChromaDB'
description: 'Instantiates a chroma database server.'
branding:
  icon: 'database'
  color: 'yellow'

runs:
  using: 'composite'
  steps:
    - name: Setup sparse-checkout
      run: |
        git clone --no-checkout https://github.com/CakeCrusher/chroma
        cd chroma
        git sparse-checkout init --cone
        git sparse-checkout set '*' '!clients'
        git checkout main
      shell: bash

    - name: Setup C++ compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
      shell: bash

    - name: Start server by running docker-compose
      run: cd ./chroma && docker-compose up -d
      shell: bash

    - name: Wait for server to be ready
      run: |
        while ! curl -s http://localhost:8000 > /dev/null; do
          echo "Waiting for server..."
          sleep 5
        done
      shell: bash
