name: 'ChromaDB'
description: 'Instantiates a chroma database server.'
branding:
  icon: 'database'
  color: 'yellow'

runs:
  using: 'composite'
  steps:
    - name: Checkout ChromaDB repository
      uses: actions/checkout@v2
      with:
        repository: 'chroma-core/chroma'
        path: './chroma'

    - name: Remove clients directory
      run: rm -rf ./chroma/clients
      shell: bash

    - name: Setup C++ compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
      shell: bash

    - name: Start server by running docker-compose
      run: cd ./chroma && docker-compose up -d
      shell: bash

    - name: Wait for server to be ready
      run: |
        while ! curl -s http://localhost:8000 > /dev/null; do
          echo "Waiting for server..."
          sleep 5
        done
      shell: bash
